theme = "onedark"

[editor]
mouse = false
bufferline = 'multiple'
true-color = true

[editor.lsp]
display-messages = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.insert]
"C-c" = "normal_mode"

[keys.normal]
0 = "goto_line_start"
esc = ["collapse_selection", "keep_primary_selection"]
D = ["ensure_selections_forward", "extend_to_line_end", "delete_selection"]
C = ["ensure_selections_forward", "extend_to_line_end", "change_selection"]
Y = ["goto_line_start", "ensure_selections_forward", "extend_to_line_bounds", "yank", "paste_after"]
F = ["select_all", "select_regex"]

[editor.cursor-shape]
insert = "bar"